version: '3.5'

services:

  ssl-vision-client:
    image: robocupssl/ssl-vision-client:latest
    command:
      - "-visionAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_MAIN_PORT}"
      - "-visualizationAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_VIZ_PORT}"
      - "-address"
      - ":${WEB_VISION_UI_PORT}"
    ports:
      - "${WEB_VISION_UI_PORT}:${WEB_VISION_UI_PORT}"
    networks:
      - simulation
    # network_mode: "host"
    depends_on:
      - sim

  # ssl-game-controller:
  #   image: robocupssl/ssl-game-controller:latest
  #   command:
  #     - "-visionAddress"
  #     - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_MAIN_PORT}"
  #     - "-trackerAddress"
  #     - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_MAIN_PORT}"
  #     - "-publishAddress"
  #     - "${GC_PUBLISH_ADDR}:${GC_PUBLISH_PORT}"
  #     - "-address"
  #     - ":${WEB_GC_UI_PORT}"
  #   ports:
  #     - "${WEB_GC_UI_PORT}:${WEB_GC_UI_PORT}"
  #   networks:
  #     - simulation
  #   depends_on:
  #     - sim

  sim:
    image: roboticserlangen/simulatorcli:commit-6a4e1c06533b
    command:
      - "-geometry"
      - "2020B"
    networks:
      - simulation


  controller:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/var/controller
    tty: true
    ports:
      - "8080:8080"
    networks:
      - simulation

  # game-viewer:
  #   build: ../GameViewer
  #   volumes:
  #     - ../GameViewer/:/var/GameViewer
  #   tty: true
  #   ports:
  #     - "5173:5173"
  #   networks:
  #     - simulation
  #   depends_on:
  #     - controller

networks:
  simulation: