version: '3.5'

services:

  ssl-vision-client:
    image: robocupssl/ssl-vision-client:latest
    command:
      - "-visionAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_MAIN_PORT}"
      - "-visualizationAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_VIZ_PORT}"
      - "-address"
      - ":${WEB_VISION_UI_PORT}"
    ports:
      - "${WEB_VISION_UI_PORT}:${WEB_VISION_UI_PORT}"
    networks:
      - simulation
    # network_mode: "host"
    depends_on:
      - grsim

  # ssl-game-controller:
  #   image: robocupssl/ssl-game-controller:latest
  #   command:
  #     - "-visionAddress"
  #     - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_MAIN_PORT}"
  #     - "-trackerAddress"
  #     - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_MAIN_PORT}"
  #     - "-publishAddress"
  #     - "${GC_PUBLISH_ADDR}:${GC_PUBLISH_PORT}"
  #     - "-address"
  #     - ":${WEB_GC_UI_PORT}"
  #   ports:
  #     - "${WEB_GC_UI_PORT}:${WEB_GC_UI_PORT}"
  #   networks:
  #     - simulation
  #   depends_on:
  #     - grsim

  grsim:
    image: roboticserlangen/simulatorcli:commit-6a4e1c06533b
    command:
      - "-geometry"
      - "2020B"
    networks:
      - simulation


  controller:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/var/controller
    tty: true
    ports:
      - "8080:8080"
    networks:
      - simulation
    # network_mode: "host"

  # game-viewer:
  #   build: ../GameViewer
  #   volumes:
  #     - ../GameViewer/:/var/GameViewer
  #   tty: true
  #   ports:
  #     - "5173:5173"
  #   networks:
  #     - simulation
  #   depends_on:
  #     - controller

  #ssl-status-board:
  #  image: robocupssl/ssl-status-board:latest
  #  command: -refereeAddress 224.5.23.1:11003
  #  ports:
  #    - "8084:8082"
  #  networks:
  #    - simulation

  #ssl-game-controller:
  #  image: bobrik/socat:latest
  #  command: 'TCP4-LISTEN:8083,fork TCP4:simulator:50543'
  #  ports:
  #    - "8083:8083"
  #  networks:
  #    - simulation
  # ssl-remote-control-yellow:
  #   image: "robocupssl/ssl-remote-control:1.1.3"
  #   command:
  #     - "-address"
  #     - ":8084"
  #     - "-refereeAddress"
  #     - "224.5.23.1:11003"
  #     - "-team"
  #     - "YELLOW"
  #   networks:
  #     - simulation
  #   ports:
  #     - "8084:8084/tcp"

networks:
  simulation:

# Is the port numbering the same as in grSim, i.e:
# GRSIM_COMMAND_LISTEN_PORT           = 20011
# GRSIM_BLUE_STATUS_SEND_PORT         = 30011
# GRSIM_YELLOW_STATUS_SEND_PORT       = 30012
# GRSIM_SIM_CONTROLLER_SEND_PORT      = 10300
# GRSIM_BLUE_CONTROLLER_LISTEN_PORT   = 10301
# GRSIM_YELLOW_CONTROLLER_LISTEN_PORT = 10302