// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grsim_packet.proto

package grsim

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GrSim_Packet struct {
	Commands             *GrSim_Commands    `protobuf:"bytes,1,opt,name=commands" json:"commands,omitempty"`
	Replacement          *GrSim_Replacement `protobuf:"bytes,2,opt,name=replacement" json:"replacement,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GrSim_Packet) Reset()         { *m = GrSim_Packet{} }
func (m *GrSim_Packet) String() string { return proto.CompactTextString(m) }
func (*GrSim_Packet) ProtoMessage()    {}
func (*GrSim_Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_0419c289fd58652c, []int{0}
}

func (m *GrSim_Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrSim_Packet.Unmarshal(m, b)
}
func (m *GrSim_Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrSim_Packet.Marshal(b, m, deterministic)
}
func (m *GrSim_Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrSim_Packet.Merge(m, src)
}
func (m *GrSim_Packet) XXX_Size() int {
	return xxx_messageInfo_GrSim_Packet.Size(m)
}
func (m *GrSim_Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_GrSim_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_GrSim_Packet proto.InternalMessageInfo

func (m *GrSim_Packet) GetCommands() *GrSim_Commands {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *GrSim_Packet) GetReplacement() *GrSim_Replacement {
	if m != nil {
		return m.Replacement
	}
	return nil
}

func init() {
	proto.RegisterType((*GrSim_Packet)(nil), "grSim_Packet")
}

func init() { proto.RegisterFile("grsim_packet.proto", fileDescriptor_0419c289fd58652c) }

var fileDescriptor_0419c289fd58652c = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0x2f, 0x2a, 0xce,
	0xcc, 0x8d, 0x2f, 0x48, 0x4c, 0xce, 0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x12,
	0x81, 0x88, 0x25, 0xe7, 0xe7, 0xe6, 0x26, 0xe6, 0xa5, 0x14, 0x43, 0x45, 0xc5, 0x21, 0xa2, 0x45,
	0xa9, 0x05, 0x39, 0x89, 0xc9, 0xa9, 0xb9, 0xa9, 0x79, 0x50, 0xe5, 0x4a, 0x85, 0x5c, 0x3c, 0xe9,
	0x45, 0xc1, 0x99, 0xb9, 0xf1, 0x01, 0x60, 0x43, 0x84, 0xb4, 0xb9, 0x38, 0x60, 0x5a, 0x25, 0x18,
	0x15, 0x18, 0x35, 0xb8, 0x8d, 0xf8, 0xf5, 0x20, 0x0a, 0x9c, 0xa1, 0xc2, 0x41, 0x70, 0x05, 0x42,
	0x26, 0x5c, 0xdc, 0x48, 0x26, 0x4a, 0x30, 0x81, 0xd5, 0x0b, 0x41, 0xd5, 0x07, 0x21, 0x64, 0x82,
	0x90, 0x95, 0x39, 0xb1, 0x47, 0xb1, 0x82, 0x5d, 0x03, 0x08, 0x00, 0x00, 0xff, 0xff, 0xce, 0x91,
	0xb2, 0x91, 0xbf, 0x00, 0x00, 0x00,
}
