// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grsim_robotstatus.proto

package grsim

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Robots_Status struct {
	RobotsStatus         []*Robot_Status `protobuf:"bytes,1,rep,name=robots_status,json=robotsStatus" json:"robots_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Robots_Status) Reset()         { *m = Robots_Status{} }
func (m *Robots_Status) String() string { return proto.CompactTextString(m) }
func (*Robots_Status) ProtoMessage()    {}
func (*Robots_Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_a12371cd6e9a31d0, []int{0}
}

func (m *Robots_Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Robots_Status.Unmarshal(m, b)
}
func (m *Robots_Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Robots_Status.Marshal(b, m, deterministic)
}
func (m *Robots_Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Robots_Status.Merge(m, src)
}
func (m *Robots_Status) XXX_Size() int {
	return xxx_messageInfo_Robots_Status.Size(m)
}
func (m *Robots_Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Robots_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Robots_Status proto.InternalMessageInfo

func (m *Robots_Status) GetRobotsStatus() []*Robot_Status {
	if m != nil {
		return m.RobotsStatus
	}
	return nil
}

type Robot_Status struct {
	RobotId              *int32   `protobuf:"varint,1,req,name=robot_id,json=robotId" json:"robot_id,omitempty"`
	Infrared             *bool    `protobuf:"varint,2,req,name=infrared" json:"infrared,omitempty"`
	FlatKick             *bool    `protobuf:"varint,3,req,name=flat_kick,json=flatKick" json:"flat_kick,omitempty"`
	ChipKick             *bool    `protobuf:"varint,4,req,name=chip_kick,json=chipKick" json:"chip_kick,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Robot_Status) Reset()         { *m = Robot_Status{} }
func (m *Robot_Status) String() string { return proto.CompactTextString(m) }
func (*Robot_Status) ProtoMessage()    {}
func (*Robot_Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_a12371cd6e9a31d0, []int{1}
}

func (m *Robot_Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Robot_Status.Unmarshal(m, b)
}
func (m *Robot_Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Robot_Status.Marshal(b, m, deterministic)
}
func (m *Robot_Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Robot_Status.Merge(m, src)
}
func (m *Robot_Status) XXX_Size() int {
	return xxx_messageInfo_Robot_Status.Size(m)
}
func (m *Robot_Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Robot_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Robot_Status proto.InternalMessageInfo

func (m *Robot_Status) GetRobotId() int32 {
	if m != nil && m.RobotId != nil {
		return *m.RobotId
	}
	return 0
}

func (m *Robot_Status) GetInfrared() bool {
	if m != nil && m.Infrared != nil {
		return *m.Infrared
	}
	return false
}

func (m *Robot_Status) GetFlatKick() bool {
	if m != nil && m.FlatKick != nil {
		return *m.FlatKick
	}
	return false
}

func (m *Robot_Status) GetChipKick() bool {
	if m != nil && m.ChipKick != nil {
		return *m.ChipKick
	}
	return false
}

func init() {
	proto.RegisterType((*Robots_Status)(nil), "Robots_Status")
	proto.RegisterType((*Robot_Status)(nil), "Robot_Status")
}

func init() { proto.RegisterFile("grsim_robotstatus.proto", fileDescriptor_a12371cd6e9a31d0) }

var fileDescriptor_a12371cd6e9a31d0 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xb1, 0x0e, 0x82, 0x30,
	0x14, 0x45, 0x03, 0x48, 0xc0, 0x27, 0x2c, 0x5d, 0xac, 0xba, 0x10, 0x26, 0x26, 0x06, 0x3e, 0x41,
	0x27, 0xe3, 0x56, 0x37, 0x97, 0x06, 0x41, 0xb4, 0x41, 0x2d, 0x69, 0xeb, 0xec, 0xaf, 0x9b, 0xbe,
	0x67, 0x8c, 0xe3, 0x3d, 0xe7, 0x2c, 0x17, 0x96, 0x57, 0x63, 0xd5, 0x43, 0x1a, 0x7d, 0xd6, 0xce,
	0xba, 0xd6, 0xbd, 0x6c, 0x3d, 0x19, 0xed, 0x74, 0xb9, 0x83, 0x5c, 0x20, 0x94, 0x47, 0xc4, 0xac,
	0x81, 0x9c, 0x2a, 0x49, 0x1d, 0x0f, 0x8a, 0xa8, 0x5a, 0x34, 0x79, 0x8d, 0xd9, 0xb7, 0x12, 0x19,
	0x35, 0xb4, 0xca, 0x37, 0x64, 0xff, 0x96, 0xad, 0x20, 0x45, 0x2f, 0x55, 0xcf, 0x83, 0x22, 0xac,
	0x62, 0x91, 0xe0, 0xde, 0xf7, 0x6c, 0x0d, 0xa9, 0x7a, 0x0e, 0xa6, 0x35, 0x97, 0x9e, 0x87, 0x45,
	0x58, 0xa5, 0xe2, 0xb7, 0xd9, 0x06, 0xe6, 0xc3, 0xbd, 0x75, 0x72, 0x54, 0xdd, 0xc8, 0x23, 0x92,
	0x1e, 0x1c, 0x54, 0x37, 0x7a, 0xd9, 0xdd, 0xd4, 0x44, 0x72, 0x46, 0xd2, 0x03, 0x2f, 0xb7, 0xc9,
	0x29, 0xc6, 0x83, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb6, 0xdb, 0x03, 0x85, 0xe8, 0x00, 0x00,
	0x00,
}
