// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grsim_commands.proto

package grsim

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GrSim_Robot_Command struct {
	Id                   *uint32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Kickspeedx           *float32 `protobuf:"fixed32,2,req,name=kickspeedx" json:"kickspeedx,omitempty"`
	Kickspeedz           *float32 `protobuf:"fixed32,3,req,name=kickspeedz" json:"kickspeedz,omitempty"`
	Veltangent           *float32 `protobuf:"fixed32,4,req,name=veltangent" json:"veltangent,omitempty"`
	Velnormal            *float32 `protobuf:"fixed32,5,req,name=velnormal" json:"velnormal,omitempty"`
	Velangular           *float32 `protobuf:"fixed32,6,req,name=velangular" json:"velangular,omitempty"`
	Spinner              *bool    `protobuf:"varint,7,req,name=spinner" json:"spinner,omitempty"`
	Wheelsspeed          *bool    `protobuf:"varint,8,req,name=wheelsspeed" json:"wheelsspeed,omitempty"`
	Wheel1               *float32 `protobuf:"fixed32,9,opt,name=wheel1" json:"wheel1,omitempty"`
	Wheel2               *float32 `protobuf:"fixed32,10,opt,name=wheel2" json:"wheel2,omitempty"`
	Wheel3               *float32 `protobuf:"fixed32,11,opt,name=wheel3" json:"wheel3,omitempty"`
	Wheel4               *float32 `protobuf:"fixed32,12,opt,name=wheel4" json:"wheel4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrSim_Robot_Command) Reset()         { *m = GrSim_Robot_Command{} }
func (m *GrSim_Robot_Command) String() string { return proto.CompactTextString(m) }
func (*GrSim_Robot_Command) ProtoMessage()    {}
func (*GrSim_Robot_Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2035e88e10aeee8, []int{0}
}

func (m *GrSim_Robot_Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrSim_Robot_Command.Unmarshal(m, b)
}
func (m *GrSim_Robot_Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrSim_Robot_Command.Marshal(b, m, deterministic)
}
func (m *GrSim_Robot_Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrSim_Robot_Command.Merge(m, src)
}
func (m *GrSim_Robot_Command) XXX_Size() int {
	return xxx_messageInfo_GrSim_Robot_Command.Size(m)
}
func (m *GrSim_Robot_Command) XXX_DiscardUnknown() {
	xxx_messageInfo_GrSim_Robot_Command.DiscardUnknown(m)
}

var xxx_messageInfo_GrSim_Robot_Command proto.InternalMessageInfo

func (m *GrSim_Robot_Command) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *GrSim_Robot_Command) GetKickspeedx() float32 {
	if m != nil && m.Kickspeedx != nil {
		return *m.Kickspeedx
	}
	return 0
}

func (m *GrSim_Robot_Command) GetKickspeedz() float32 {
	if m != nil && m.Kickspeedz != nil {
		return *m.Kickspeedz
	}
	return 0
}

func (m *GrSim_Robot_Command) GetVeltangent() float32 {
	if m != nil && m.Veltangent != nil {
		return *m.Veltangent
	}
	return 0
}

func (m *GrSim_Robot_Command) GetVelnormal() float32 {
	if m != nil && m.Velnormal != nil {
		return *m.Velnormal
	}
	return 0
}

func (m *GrSim_Robot_Command) GetVelangular() float32 {
	if m != nil && m.Velangular != nil {
		return *m.Velangular
	}
	return 0
}

func (m *GrSim_Robot_Command) GetSpinner() bool {
	if m != nil && m.Spinner != nil {
		return *m.Spinner
	}
	return false
}

func (m *GrSim_Robot_Command) GetWheelsspeed() bool {
	if m != nil && m.Wheelsspeed != nil {
		return *m.Wheelsspeed
	}
	return false
}

func (m *GrSim_Robot_Command) GetWheel1() float32 {
	if m != nil && m.Wheel1 != nil {
		return *m.Wheel1
	}
	return 0
}

func (m *GrSim_Robot_Command) GetWheel2() float32 {
	if m != nil && m.Wheel2 != nil {
		return *m.Wheel2
	}
	return 0
}

func (m *GrSim_Robot_Command) GetWheel3() float32 {
	if m != nil && m.Wheel3 != nil {
		return *m.Wheel3
	}
	return 0
}

func (m *GrSim_Robot_Command) GetWheel4() float32 {
	if m != nil && m.Wheel4 != nil {
		return *m.Wheel4
	}
	return 0
}

type GrSim_Commands struct {
	Timestamp            *float64               `protobuf:"fixed64,1,req,name=timestamp" json:"timestamp,omitempty"`
	Isteamyellow         *bool                  `protobuf:"varint,2,req,name=isteamyellow" json:"isteamyellow,omitempty"`
	RobotCommands        []*GrSim_Robot_Command `protobuf:"bytes,3,rep,name=robot_commands,json=robotCommands" json:"robot_commands,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GrSim_Commands) Reset()         { *m = GrSim_Commands{} }
func (m *GrSim_Commands) String() string { return proto.CompactTextString(m) }
func (*GrSim_Commands) ProtoMessage()    {}
func (*GrSim_Commands) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2035e88e10aeee8, []int{1}
}

func (m *GrSim_Commands) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrSim_Commands.Unmarshal(m, b)
}
func (m *GrSim_Commands) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrSim_Commands.Marshal(b, m, deterministic)
}
func (m *GrSim_Commands) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrSim_Commands.Merge(m, src)
}
func (m *GrSim_Commands) XXX_Size() int {
	return xxx_messageInfo_GrSim_Commands.Size(m)
}
func (m *GrSim_Commands) XXX_DiscardUnknown() {
	xxx_messageInfo_GrSim_Commands.DiscardUnknown(m)
}

var xxx_messageInfo_GrSim_Commands proto.InternalMessageInfo

func (m *GrSim_Commands) GetTimestamp() float64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *GrSim_Commands) GetIsteamyellow() bool {
	if m != nil && m.Isteamyellow != nil {
		return *m.Isteamyellow
	}
	return false
}

func (m *GrSim_Commands) GetRobotCommands() []*GrSim_Robot_Command {
	if m != nil {
		return m.RobotCommands
	}
	return nil
}

func init() {
	proto.RegisterType((*GrSim_Robot_Command)(nil), "grSim_Robot_Command")
	proto.RegisterType((*GrSim_Commands)(nil), "grSim_Commands")
}

func init() { proto.RegisterFile("grsim_commands.proto", fileDescriptor_a2035e88e10aeee8) }

var fileDescriptor_a2035e88e10aeee8 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xbd, 0x4e, 0xf3, 0x30,
	0x14, 0x86, 0x15, 0xf7, 0xeb, 0xdf, 0xe9, 0xcf, 0xe0, 0xaf, 0x42, 0x67, 0x40, 0x28, 0xea, 0x94,
	0xa9, 0x12, 0x6d, 0x37, 0x36, 0xb8, 0x03, 0xb3, 0xb1, 0x54, 0xa6, 0xb1, 0x82, 0x55, 0xff, 0x44,
	0xb6, 0x69, 0xa1, 0x37, 0xc1, 0x25, 0x72, 0x2b, 0xa8, 0x6e, 0x9a, 0xa4, 0x88, 0xf1, 0x3c, 0x4f,
	0x8e, 0x62, 0xbf, 0xaf, 0x61, 0x56, 0x38, 0x2f, 0xf5, 0x66, 0x6b, 0xb5, 0xe6, 0x26, 0xf7, 0x8b,
	0xd2, 0xd9, 0x60, 0xe7, 0xdf, 0x04, 0xfe, 0x17, 0xee, 0x59, 0xea, 0x0d, 0xb3, 0xaf, 0x36, 0x6c,
	0x9e, 0xce, 0x9a, 0x4e, 0x81, 0xc8, 0x1c, 0x93, 0x94, 0x64, 0x13, 0x46, 0x64, 0x4e, 0xef, 0x00,
	0x76, 0x72, 0xbb, 0xf3, 0xa5, 0x10, 0xf9, 0x07, 0x92, 0x94, 0x64, 0x84, 0xb5, 0xc8, 0x95, 0x3f,
	0x62, 0xe7, 0x97, 0x3f, 0x9e, 0xfc, 0x5e, 0xa8, 0xc0, 0x4d, 0x21, 0x4c, 0xc0, 0x7f, 0x67, 0xdf,
	0x10, 0x7a, 0x0b, 0xc3, 0xbd, 0x50, 0xc6, 0x3a, 0xcd, 0x15, 0x76, 0xa3, 0x6e, 0x40, 0xb5, 0xcd,
	0x4d, 0xf1, 0xae, 0xb8, 0xc3, 0x5e, 0xbd, 0x5d, 0x11, 0x8a, 0xd0, 0xf7, 0xa5, 0x34, 0x46, 0x38,
	0xec, 0xa7, 0x24, 0x1b, 0xb0, 0xcb, 0x48, 0x53, 0x18, 0x1d, 0xde, 0x84, 0x50, 0x3e, 0x9e, 0x03,
	0x07, 0xd1, 0xb6, 0x11, 0xbd, 0x81, 0x5e, 0x1c, 0xef, 0x71, 0x98, 0x26, 0x19, 0x61, 0xd5, 0x54,
	0xf3, 0x25, 0x42, 0x8b, 0x2f, 0x6b, 0xbe, 0xc2, 0x51, 0x8b, 0xaf, 0x6a, 0xbe, 0xc6, 0x71, 0x8b,
	0xaf, 0xe7, 0x5f, 0x09, 0x4c, 0xcf, 0x09, 0x57, 0xd9, 0xfa, 0xd3, 0x65, 0x83, 0xd4, 0xc2, 0x07,
	0xae, 0xcb, 0x98, 0x71, 0xc2, 0x1a, 0x40, 0xe7, 0x30, 0x96, 0x3e, 0x08, 0xae, 0x3f, 0x85, 0x52,
	0xf6, 0x10, 0xc3, 0x1e, 0xb0, 0x2b, 0x46, 0x1f, 0x60, 0xea, 0x62, 0x5f, 0x97, 0x3a, 0xb1, 0x93,
	0x76, 0xb2, 0xd1, 0x72, 0xb6, 0xf8, 0xa3, 0x4c, 0x36, 0x89, 0xdf, 0x5e, 0x7e, 0xff, 0xd8, 0x7f,
	0xe9, 0xc6, 0xb7, 0xf0, 0x13, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xe7, 0x64, 0xb9, 0x13, 0x02, 0x00,
	0x00,
}
