// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssl_wrapper_tracked.proto

package ssl_vision

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A wrapper packet containing meta data of the source
// Also serves for the possibility to extend the protocol later
type TrackerWrapperPacket struct {
	// A random UUID of the source that is kept constant at the source while running
	// If multiple sources are broadcasting to the same network, this id can be used to identify individual sources
	Uuid *string `protobuf:"bytes,1,req,name=uuid" json:"uuid,omitempty"`
	// The name of the source software that is producing this messages.
	SourceName *string `protobuf:"bytes,2,opt,name=source_name,json=sourceName" json:"source_name,omitempty"`
	// The tracked frame
	TrackedFrame         *TrackedFrame `protobuf:"bytes,3,opt,name=tracked_frame,json=trackedFrame" json:"tracked_frame,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TrackerWrapperPacket) Reset()         { *m = TrackerWrapperPacket{} }
func (m *TrackerWrapperPacket) String() string { return proto.CompactTextString(m) }
func (*TrackerWrapperPacket) ProtoMessage()    {}
func (*TrackerWrapperPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_63a907d048b876d8, []int{0}
}

func (m *TrackerWrapperPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackerWrapperPacket.Unmarshal(m, b)
}
func (m *TrackerWrapperPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackerWrapperPacket.Marshal(b, m, deterministic)
}
func (m *TrackerWrapperPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackerWrapperPacket.Merge(m, src)
}
func (m *TrackerWrapperPacket) XXX_Size() int {
	return xxx_messageInfo_TrackerWrapperPacket.Size(m)
}
func (m *TrackerWrapperPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackerWrapperPacket.DiscardUnknown(m)
}

var xxx_messageInfo_TrackerWrapperPacket proto.InternalMessageInfo

func (m *TrackerWrapperPacket) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *TrackerWrapperPacket) GetSourceName() string {
	if m != nil && m.SourceName != nil {
		return *m.SourceName
	}
	return ""
}

func (m *TrackerWrapperPacket) GetTrackedFrame() *TrackedFrame {
	if m != nil {
		return m.TrackedFrame
	}
	return nil
}

func init() {
	proto.RegisterType((*TrackerWrapperPacket)(nil), "TrackerWrapperPacket")
}

func init() { proto.RegisterFile("ssl_wrapper_tracked.proto", fileDescriptor_63a907d048b876d8) }

var fileDescriptor_63a907d048b876d8 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x2e, 0xce, 0x89,
	0x2f, 0x2f, 0x4a, 0x2c, 0x28, 0x48, 0x2d, 0x8a, 0x2f, 0x29, 0x4a, 0x4c, 0xce, 0x4e, 0x4d, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x06, 0x49, 0xa5, 0xa4, 0x96, 0xa4, 0x26, 0x97, 0x64,
	0xe6, 0xe7, 0xa1, 0x4a, 0x2a, 0xd5, 0x73, 0x89, 0x84, 0x80, 0x05, 0x8a, 0xc2, 0x21, 0x9a, 0x03,
	0x40, 0x9c, 0x12, 0x21, 0x21, 0x2e, 0x96, 0xd2, 0xd2, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x26, 0x0d,
	0xce, 0x20, 0x30, 0x5b, 0x48, 0x9e, 0x8b, 0xbb, 0x38, 0xbf, 0xb4, 0x28, 0x39, 0x35, 0x3e, 0x2f,
	0x31, 0x37, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x88, 0x0b, 0x22, 0xe4, 0x97, 0x98, 0x9b,
	0x2a, 0x64, 0xc4, 0xc5, 0x0b, 0x35, 0x3d, 0x3e, 0xad, 0x08, 0xa4, 0x84, 0x59, 0x81, 0x51, 0x83,
	0xdb, 0x88, 0x57, 0x0f, 0x62, 0x45, 0x8a, 0x1b, 0x48, 0x30, 0x88, 0xa7, 0x04, 0x89, 0xe7, 0xc4,
	0x13, 0xc5, 0x05, 0x72, 0x5f, 0x59, 0x66, 0x71, 0x66, 0x7e, 0x1e, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x1d, 0x18, 0x65, 0x74, 0xc7, 0x00, 0x00, 0x00,
}
